# Generated by Django 5.1.1 on 2024-09-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Handler',
        ),
    ]
