# Generated by Django 5.1.1 on 2024-09-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_delete_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('token', models.CharField(max_length=20)),
                ('new_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
