# Generated by Django 5.1.1 on 2024-09-23 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_alter_handler_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='url',
            field=models.URLField(unique=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
