# Generated by Django 5.1.1 on 2024-09-23 08:02

import url.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_alter_handler_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='url',
            field=models.URLField(unique=True, validators=[url.models.custom_url_validator]),
        ),
    ]
