# Generated by Django 5.1.1 on 2024-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0006_alter_handler_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
