# Generated by Django 5.1.1 on 2025-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0008_handler_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='castom_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='handler',
            name='new_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
